MxOnline/urls.py
import xadmin
from django.urls import path, re_path
from django.conf.urls import include
from django.views.static import serve

from .settings import MEDIA_ROOT, DEBUG
from users.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('xadmin/', xadmin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('captcha/', include('captcha.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('orgs/', include('organization.urls', namespace='orgs')),
    path('oper/', include('operation.urls', namespace='oper')),
    path('courses/', include('courses.urls', namespace='courses')),
    re_path('media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    #
]

if not DEBUG:
    from .settings import STATIC_ROOT
    urlpatterns.append(re_path('static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}))

apps/courses/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'Sheldon'
__date__ = '2018/11/15 15:31'
from django.urls import path

from .views import CourseListView, CourseCommentView, CourseDetailView, CourseVideoView, CoursePlayView


app_name = 'courses'
urlpatterns = [
    path('list/', CourseListView.as_view(), name='list'),
    path('detail/<int:course_id>', CourseDetailView.as_view(), name='detail'),
    path('comment/<int:course_id>', CourseCommentView.as_view(), name='comment'),
    path('video/<int:course_id>', CourseVideoView.as_view(), name='video'),
    path('play/<int:video_id>', CoursePlayView.as_view(), name='play'),
]

apps/operation/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'Sheldon'
__date__ = '2018/10/16 16:50'

from django.urls import path

from .views import AddUserAskView, AddUserFavView, AddCourseCommentView, SendPinCodeView

app_name = 'oper'
urlpatterns = [
    path('addask/', AddUserAskView.as_view(), name='user_ask'),
    path('addfav/', AddUserFavView.as_view(), name='add_fav'),
    path('addCourseComment/', AddCourseCommentView.as_view(), name='add_comment'),
    path('sendpin/', SendPinCodeView.as_view(), name='send_pin')
]

apps/users/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'Sheldon'
__date__ = '2018/10/9 9:33'

from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'users'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('pwd_reset/', views.PwdResetView.as_view(), name='pwd_reset'),
    path('activate/<slug:active_code>', views.ActivateUser.as_view(), name='activate'),
    path('forget/', views.ForgetPwdView.as_view(), name='forget'),
    path('reset/<slug:reset_code>', views.ResetView.as_view(), name='reset'),
    path('expired/', TemplateView.as_view(template_name='users/url_expired.html'), name='expired'),
    path('mail_sent/', TemplateView.as_view(template_name='users/send_success.html'), name='mail_sent'),
    # 个人中心
    path('home/', views.UserInfoCenter.as_view(), name='home'),
    # 我的课程
    path('courses/', views.UserCourseView.as_view(), name='course'),
    # 我的收藏-机构
    path('fav/org/', views.UserFavOrgView.as_view(), name='favorg'),
    # 我的收藏-课程
    path('fav/course/', views.UserFavCourseView.as_view(), name='favcourse'),
    # 我的收藏-教师
    path('fav/teacher/', views.UserFavTeacherView.as_view(), name='favteacher'),
    # 消息中心
    path('message/', views.UserMessageView.as_view(), name='message'),
    path('uploadimage/', views.UploadImageView.as_view(), name='upload_img'),
    path('update_email/', views.UpdateEmailView.as_view(), name='update_email'),
    path('updatepwd/', views.UpdatePasswordView.as_view(), name='updatepwd'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

extra_apps/DjangoUeditor/urls.py
#coding:utf-8
from .views import get_ueditor_controller
from django.urls import path

urlpatterns = [
    path('controller/', get_ueditor_controller),
]

apps/courses/models.py
# _*_ coding:utf-8 _*-
from datetime import datetime
from django.db import models

from organization.models import CourseOrg, Teacher
from DjangoUeditor.models import UEditorField
# Create your models here.


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name='课程机构', null=True, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, verbose_name='授课教师', null=True, blank=True, on_delete=models.CASCADE)
    is_banner = models.BooleanField(verbose_name='是否轮播', null=True, blank=True, default=False)
    name = models.CharField(max_length=50, verbose_name="课程名")
    desc = models.CharField(max_length=300, verbose_name="课程描述")
    category = models.CharField(max_length=20, verbose_name="课程类别", default="后端开发")
    #detail = models.TextField(verbose_name="课程详情", default='')
    detail = UEditorField(verbose_name="课程详情", height=100, width=500, default='',
                          imagePath="courses/ueditor/", filePath="courses/ueditor")
    degree = models.CharField(choices=(("cj", "初级"), ("zj", "中级"), ("gj", "高级")), verbose_name="课程难度", max_length=2)
    learn_times = models.IntegerField(default=0, verbose_name="学习时长(分钟数)")
    students = models.IntegerField(default=0, verbose_name="学习人数")
    fav_nums = models.IntegerField(default=0, verbose_name="收藏")
    image = models.ImageField(verbose_name="封面图", upload_to="courses/%Y/%m", max_length=100, null=True, blank=True)
    click_nums = models.IntegerField(default=0, verbose_name="点击量")
    tag = models.CharField(default='', verbose_name="课程标签", max_length=10)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="课程添加时间")
    instruction = models.CharField(max_length=300, verbose_name="课程须知", default='', null=True, blank=True)
    introduction = models.CharField(max_length=300, verbose_name="老师引言", default='', null=True, blank=True)
    announcement = models.CharField(max_length=300, verbose_name="课程公告", default='', null=True, blank=True)

    class Meta:
        verbose_name_plural = verbose_name = "课程"

#   获取课程章节数
    def get_zj_nums(self):
        return self.lesson_set.all().count()

#   获取当前的学生
    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

#   获取当前的学生
    def get_students_cnt(self):
        return self.usercourse_set.all().count()

#    获取当前课程的章节明细
    def get_course_lessons(self):
        return self.lesson_set.all()

    def __str__(self):
        return self.name


class BannerCourse(Course):
    class Meta:
        proxy = True
        verbose_name_plural = verbose_name = '课程轮播图'


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name="课程", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name="章节名")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = verbose_name_plural = "章节"

    def get_video_list(self):
        return self.video_set.all()

    def __str__(self):
        return f"{self.course}-{self.name}"


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name="章节", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name="视频名")
    duration = models.IntegerField(default=0, verbose_name="学习时长(分钟)")
    url = models.CharField(max_length=200, verbose_name="访问地址", default="")

    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = verbose_name_plural = "视频"

    def __str__(self):
        return f"{self.lesson}-{self.name}"


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name="课程", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name="名称")
    download = models.FileField(upload_to="course/resource/%Y/%m", verbose_name="资源文件", max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = verbose_name_plural = "课程资源"

    def __str__(self):
        return f"{self.course}-{self.name}"

apps/courses/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View
from django.db.models import Q

from django.core.paginator import Paginator, PageNotAnInteger

from .models import Course, CourseResource, Video
from operation.models import UserFavorite, UserCourse
from MxOnline.settings import FAV_TYPE
from utils.mixin_utils import LoginRequiredMixin
# Create your views here.


class CourseListView(View):
    cur_page = 'course_list'
    template_name = 'courses/course-list.html'

    def get(self, request):
        all_courses = Course.objects.all().order_by('add_time')

        search_keywords = request.GET.get('keywords', '')
        if search_keywords:
            all_courses = all_courses.filter(Q(name__icontains=search_keywords) |
                                             Q(teacher__name__icontains=search_keywords) |
                                             Q(desc__icontains=search_keywords)).distinct()
        sort_type = request.GET.get('sort', '')
        hot_courses = all_courses.order_by('-click_nums')
        if sort_type == 'students':
            all_courses = all_courses.order_by('-students')
        elif sort_type == 'hot':
            all_courses = hot_courses
        hot_courses = hot_courses[:3]
        try:
            page = int(request.GET.get('page', 1))
        except PageNotAnInteger:
            page = 1
        page_content = Paginator(all_courses, per_page=8)
        courses_list = page_content.page(number=page)

        context = {
            'courses_list': courses_list,
            'hot_courses': hot_courses,
            'cur_page': self.cur_page,
            'sort': sort_type,
        }
        return render(request=request, template_name=self.template_name, context=context)


class CourseDetailView(View):
    '''
    课程详情页
    '''
    template_name = 'courses/course-detail.html'

    def get(self, request, course_id):
        course = Course.objects.get(id=course_id)
        course.click_nums += 1
        course.save()
        company = course.course_org
        if course.tag:
            relate_courses = Course.objects.filter(tag=course.tag).exclude(id=course.id).order_by("students")[:2]
        else:
            relate_courses = []
        has_fav_org = has_fav_course = False
        if request.user.is_authenticated:
            existed_rec = UserFavorite.objects.filter(user=request.user, fav_id=course_id, fav_type=FAV_TYPE['course'])
            if existed_rec:
                has_fav_course = True
            existed_rec = UserFavorite.objects.filter(user=request.user, fav_id=company.id, fav_type=FAV_TYPE['corg'])
            if existed_rec:
                has_fav_org = True
        context = {
            'has_fav_org': has_fav_org,
            'relate_courses': relate_courses,
            'has_fav_course': has_fav_course,
            'course': course,
            'company': company,
        }
        return render(request=request, template_name=self.template_name, context=context)


class CourseCommentView(LoginRequiredMixin, View):

    cur_page = 'courseComment'
    template_name = 'courses/course-comment.html'

    def get(self, request, course_id):
        course = Course.objects.get(id=course_id)
        course.click_nums += 1
        course.save()
        user_courses = UserCourse.objects.filter(id=course_id)
        user_ids = [user_course.user.id for user_course in user_courses]
        all_courses = UserCourse.objects.filter(user_id__in=user_ids)

        course_ids = [course.id for course in all_courses]
        related_courses = Course.objects.filter(id__in=course_ids).order_by("-click_nums")[:5]
        comment_list = course.coursecomment_set.all().order_by("-add_time")
        all_resources = CourseResource.objects.filter(course=course)
        context = {
            'course': course,
            'related_courses': related_courses,
            'comment_list': comment_list,
            'course_resources': all_resources,
            'cur_page': self.cur_page,
        }
        return render(request=request, template_name=self.template_name, context=context)


class CourseVideoView(LoginRequiredMixin, View):

    cur_page = 'courseVideo'
    template_name = 'courses/course-video.html'

    def get(self, request, course_id):
        course = Course.objects.get(id=course_id)
        course.click_nums += 1
        user_course = UserCourse.objects.filter(user=request.user, course=course)
        if not user_course:
            user_course = UserCourse(course=course, user=request.user)
            user_course.save()
            course.students += 1
        course.save()
        all_resources = CourseResource.objects.filter(course=course)

        user_courses = UserCourse.objects.filter(id=course_id)
        user_ids = [user_course.user.id for user_course in user_courses]
        all_courses = UserCourse.objects.filter(user_id__in=user_ids)
        course_ids = [course.id for course in all_courses]
        related_courses = Course.objects.filter(id__in=course_ids).order_by("-click_nums")[:5]

        context = {
            'course': course,
            'related_courses': related_courses,
            'course_resources': all_resources,
            'cur_page': self.cur_page,
        }
        return render(request=request, template_name=self.template_name, context=context)


class CoursePlayView(LoginRequiredMixin, View):

    cur_page = 'coursePlay'
    template_name = 'courses/course-play.html'

    def get(self, request, video_id):
        video = get_object_or_404(Video, pk=video_id)
        course = video.lesson.course
        course.click_nums += 1
        user_course = UserCourse.objects.filter(user=request.user, course=course)
        if not user_course:
            user_course = UserCourse(course=course, user=request.user)
            user_course.save()
            course.students += 1
        course.save()
        all_resources = CourseResource.objects.filter(course=course)

        user_courses = UserCourse.objects.filter(id=course.id)
        user_ids = [user_course.user.id for user_course in user_courses]
        all_courses = UserCourse.objects.filter(user_id__in=user_ids)
        course_ids = [course.id for course in all_courses]
        related_courses = Course.objects.filter(id__in=course_ids).order_by("-click_nums")[:5]

        context = {
            'course': course,
            'video': video,
            'related_courses': related_courses,
            'course_resources': all_resources,
            'cur_page': self.cur_page,
        }
        return render(request=request, template_name=self.template_name, context=context)

templates/courses/course-comment.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{%  static 'css/muke/course/learn-less.css' %}" />
	<link rel="stylesheet" type="text/css" href="{%  static 'css/muke/course/course-comment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{%  static 'css/muke/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{%  static 'css/muke/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{%  static 'css/muke/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{%  static 'css/mooc.css' %}" />
{% endblock %}
{% block cutom_bread %}
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'courses:list' %}">公开课程</a>></li>
				<li><a href="{% url 'courses:detail' course.id %}">课程详情</a>></li>
                <li>课程评论</li>
			</ul>
		</div>
	</div>
{% endblock %}

    <div id="main">
    {% block content %}
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_times }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.get_students_cnt }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
            <div class="content-wrap clearfix">
                <div class="content">
                    <div class="mod-tab-menu">
                        <ul class="course-menu clearfix">
                            <li><a class="ui-tabs-active " id="learnOn"  href="{% url 'courses:video'  course.id %}"><span>章节</span></a></li>
                            <li><a id="commentOn" class="active" href="{% url 'courses:comment'  course.id %}"><span>评论</span></a></li>
                        </ul>
                    </div>

                    <!--发布评论-->
                    <div id="js-pub-container" class="issques clearfix js-form">
                        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！" ></textarea>
                        </div>
                        <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                        <p class="global-errortip js-global-error"></p>
                    </div>
                    <div id="course_note">
                        <ul class="mod-post" id="comment-list">
                            {% for comment in comment_list %}
                            <li class="post-row">
                                <div class="media">
                                    <span target="_blank"><img src="{{ MEDIA_URL }}{{ comment.user.image }}" width='40' height='40' /></span>
                                </div>
                                <div class="bd">
                                    <div class="tit">
                                        <span target="_blank">{{ comment.user.nick_name }}</span>
                                    </div>
                                    <p class="cnt">{{ comment.comments }}</p>
                                    <div class="footer clearfix">
                                        <span title="创建时间" class="l timeago">时间：{{ comment.add_time }}</span>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>

                </div>
                <div class="aside r">
                    <div class="bd">

                        <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                         {% for res in course_resources %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ res.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ res.download }}" class="downcode" target="_blank" download="" data-id="{{ res.id }}" title="">下载</a>
                            </li>
                         {% endfor %}
                        </ul>
                    </div>
                        <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                            <span class="job">{{ course.teacher.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.instruction }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.introduction }}</dd>
                            </dl>
                        </div>
                    </div>


                        <div class="cp-other-learned  js-comp-tabs">
                            <div class="cp-header clearfix">
                                <h2 class="cp-tit l">该课的同学还学过</h2>
                            </div>
                            <div class="cp-body">
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                    <!-- img 200 x 112 -->
                                    <ul class="other-list">
                                        {% for related_course in related_courses %}
                                        <li class="curr">
                                            <a href="{% url 'courses:detail' related_course.id %}" target="_blank">
                                                <img src="{{ MEDIA_URL }}{{ related_course.image }}" alt="{{ related_course.name }}">
                                                <span class="name autowrap">{{ related_course.name }}</span>
                                            </a>
                                        </li>
                                    {% endfor %}
                                    </ul>
                                </div>
                                <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                    <ul class="other-list">
                                        <li class="curr">
                                            <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                                <span class="name autowrap">Java工程师</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>    </div>
            </div>
            <div class="clear"></div>

        </div>

    </div>
{% endblock %}
{% block custom_js %}
<script type="text/javascript">
    //添加评论
    $(document).ready(function() {
        $('#js-pl-submit').on('click', function () {
            var comments = $("#js-pl-textarea").val()
            if (comments == "") {
                alert("评论不能为空")
                return
            }
            $.ajax({
                cache: false,
                type: "POST",
                url: "{% url 'oper:add_comment' %}",
                data: {'course_id': {{ course.id }}, 'comments': comments},
                async: true,
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function (data) {
                    if (data.status == 'fail') {
                        if (data.msg == '用户未登录') {
                            window.location.href = "{% url 'users:login' %}";
                        } else {
                            alert(data.msg)
                        }

                    } else if (data.status == 'success') {
                        window.location.reload();//刷新当前页面.
                    }
                },
            });
        });
    });
</script>
{% endblock %}

templates/courses/course-list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load useful_tags %}
{% block title %}公开课列表 - 在线学习网{% endblock %}
{% block custom_css %}

{% endblock %}
{% block url_path %}<li>公开课</li>{% endblock %}
{% block cutom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
{% with params=request.GET.urlencode %}
<section>
	<div class="wp">
		<div class="list" style="margin-top:0;">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li {% if sort == '' %}class="active"{% endif %}><a href="{% relative_url 'sort' '' params %}">最新 </a></li>
						<li {% if sort == 'hot' %}class="active"{% endif %}><a href="{% relative_url 'sort' 'hot' params %}">最热门</a></li>
						<li {% if sort == 'students' %}class="active"{% endif %}><a href="{% relative_url 'sort' 'students' params %}">参与人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					<div class="group_list">
                        {% for course in courses_list %}
                            <div class="box">
                                <a href="{% url 'courses:detail' course.id %}">
                                    <img width="280" height="350" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'courses:detail' course.id %}">
                                        <h2>{{ course.name|truncatechars:16 }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ course.learn_times }}分钟</i></span>
                                    <span class="fr">学习人数：{{ course.students }}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href="{% url 'courses:detail' course.id %}"><span class="fl">来自{{ course.course_org }}</span></a>
                                    <span class="star fr  notlogin" data-favid="{{ course.id }}">
                                        {{ course.fav_nums }}
                                    </span>
                                </div>
                            </div>
                        {% endfor %}
					</div>
                    <div class="pageturn">
                        <ul class="pagelist">
                           {% if courses_list.has_previous %}
                               <li class="long"><a href="{% relative_url 'page' courses_list.previous_page_number params %}">上一页</a></li>
                           {% endif %}
                           {% for page in courses_list.paginator.page_range %}
                               {% if page %}
                                   <li class="{% if page == courses_list.number %}active{% endif %}"><a href="{% relative_url 'page' page params %}">{{ page }}</a></li>
                               {% else %}
                                   <li class="none"><a href="">...</a></li>
                               {% endif %}
                           {% endfor %}
                           {% if courses_list.has_next %}
                               <li class="long"><a href="{% relative_url 'page' courses_list.next_page_number params %}">下一页</a></li>
                           {% endif %}
                       </ul>
                    </div>
				</div>
                </div>
			</div>
			<div class="right layout">
				<div class="head">热门课程推荐</div>
				<div class="group_recommend">

                    {% for course in hot_courses %}
                    <dl>
						<dt>
							<a target="_blank" href="{% url 'courses:detail'  course.id %}">
								<img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href="{% url 'courses:detail'  course.id %}"><h2> {{ course.name }}</h2></a>
							<span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
						</dd>
					</dl>
                    {% endfor %}
				</div>
			</div>
		</div>
	</div>
</section>
{% endwith %}
{% endblock %}