MxOnline/urls.py
import xadmin
from django.urls import path, re_path
from django.conf.urls import include
from django.views.static import serve

from .settings import MEDIA_ROOT, DEBUG
from users.views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('xadmin/', xadmin.site.urls),
    path('ueditor/', include('DjangoUeditor.urls')),
    path('captcha/', include('captcha.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('orgs/', include('organization.urls', namespace='orgs')),
    path('oper/', include('operation.urls', namespace='oper')),
    path('courses/', include('courses.urls', namespace='courses')),
    re_path('media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    #
]

if not DEBUG:
    from .settings import STATIC_ROOT
    urlpatterns.append(re_path('static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}))

apps/courses/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'Sheldon'
__date__ = '2018/11/15 15:31'
from django.urls import path

from .views import CourseListView, CourseCommentView, CourseDetailView, CourseVideoView, CoursePlayView


app_name = 'courses'
urlpatterns = [
    path('list/', CourseListView.as_view(), name='list'),
    path('detail/<int:course_id>', CourseDetailView.as_view(), name='detail'),
    path('comment/<int:course_id>', CourseCommentView.as_view(), name='comment'),
    path('video/<int:course_id>', CourseVideoView.as_view(), name='video'),
    path('play/<int:video_id>', CoursePlayView.as_view(), name='play'),
]

apps/operation/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'Sheldon'
__date__ = '2018/10/16 16:50'

from django.urls import path

from .views import AddUserAskView, AddUserFavView, AddCourseCommentView, SendPinCodeView

app_name = 'oper'
urlpatterns = [
    path('addask/', AddUserAskView.as_view(), name='user_ask'),
    path('addfav/', AddUserFavView.as_view(), name='add_fav'),
    path('addCourseComment/', AddCourseCommentView.as_view(), name='add_comment'),
    path('sendpin/', SendPinCodeView.as_view(), name='send_pin')
]

apps/organization/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'Sheldon'
__date__ = '2018/10/9 9:25'
from django.urls import path

from .views import OrgListView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView
from .views import TeacherListView, TeacherDetailView

app_name = 'orgs'
urlpatterns = [
    path('list/', OrgListView.as_view(), name='org_list'),
    path('home/<int:org_id>', OrgHomeView.as_view(), name='home'),
    path('course/<int:org_id>', OrgCourseView.as_view(), name='course'),
    path('desc/<int:org_id>', OrgDescView.as_view(), name='desc'),
    path('org_teacher/<int:org_id>', OrgTeacherView.as_view(), name='teacher'),
    path('desc/<int:org_id>', OrgDescView.as_view(), name='desc'),
    path('teacher/list/', TeacherListView.as_view(), name='teacher_list'),
    path('teacher/detail/<int:teacher_id>', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/users/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'Sheldon'
__date__ = '2018/10/9 9:33'

from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'users'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('pwd_reset/', views.PwdResetView.as_view(), name='pwd_reset'),
    path('activate/<slug:active_code>', views.ActivateUser.as_view(), name='activate'),
    path('forget/', views.ForgetPwdView.as_view(), name='forget'),
    path('reset/<slug:reset_code>', views.ResetView.as_view(), name='reset'),
    path('expired/', TemplateView.as_view(template_name='users/url_expired.html'), name='expired'),
    path('mail_sent/', TemplateView.as_view(template_name='users/send_success.html'), name='mail_sent'),
    # 个人中心
    path('home/', views.UserInfoCenter.as_view(), name='home'),
    # 我的课程
    path('courses/', views.UserCourseView.as_view(), name='course'),
    # 我的收藏-机构
    path('fav/org/', views.UserFavOrgView.as_view(), name='favorg'),
    # 我的收藏-课程
    path('fav/course/', views.UserFavCourseView.as_view(), name='favcourse'),
    # 我的收藏-教师
    path('fav/teacher/', views.UserFavTeacherView.as_view(), name='favteacher'),
    # 消息中心
    path('message/', views.UserMessageView.as_view(), name='message'),
    path('uploadimage/', views.UploadImageView.as_view(), name='upload_img'),
    path('update_email/', views.UpdateEmailView.as_view(), name='update_email'),
    path('updatepwd/', views.UpdatePasswordView.as_view(), name='updatepwd'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

extra_apps/DjangoUeditor/urls.py
#coding:utf-8
from .views import get_ueditor_controller
from django.urls import path

urlpatterns = [
    path('controller/', get_ueditor_controller),
]

apps/users/models.py
from datetime import datetime, timedelta

# 第三方
from django.db import models
from django.contrib.auth.models import AbstractUser

# 自定义lib
# Create your models here.


class UserProfile(AbstractUser):
    nick_name = models.CharField(max_length=50, verbose_name="昵称", default="")
    birthday = models.DateField(verbose_name="生日", null=True)
    gender = models.CharField(max_length=6, choices=(("male", "男"), ("female", "女")), default="female")
    address = models.CharField(max_length=100, default="")
    mobile = models.CharField(max_length=11, null=True, blank=True)
    image = models.ImageField(verbose_name="用户头像", upload_to="image/%Y/%m", default="image/default.png",
                              max_length=100, null=True, blank=True)

    class Meta:
        verbose_name_plural = verbose_name = "用户信息"

    def get_unread_nums(self):
        from operation.models import UserMessage
        return UserMessage.objects.filter(user=self.id, has_read=False).count()

    def __str__(self):
        return self.username if self.username is not None else self.email


class EmailVerifyRecord(models.Model):
    code = models.CharField(max_length=20, verbose_name="验证码")
    email = models.EmailField(max_length=50, verbose_name="邮箱")
    valid = models.BooleanField(verbose_name='是否有效', null=True, blank=True, default=True)
    send_status = models.CharField(choices=(('succeed', '成功'), ('failed', '失败'), ('unknown', '未知')),
                                   max_length=10, verbose_name='发送状态', default='unknown')
    send_type = models.CharField(choices=(("register", "注册"), ("forget", "找回密码"), ("pincode", "验证码")),
                                 max_length=10, verbose_name="验证码类型")
    send_time = models.DateTimeField(default=datetime.now, verbose_name="发送时间")
    expired = models.DateTimeField(blank=True, null=True, verbose_name="失效时间")

    class Meta:
        verbose_name_plural = verbose_name = "邮箱验证码"

    def __str__(self):
        return f"{self.email} - {self.code}"

    def is_valid(self):
        if self.valid and self.expired < datetime.now():
            self.valid = False
            self.save()

        return self.valid


class Banner(models.Model):
    title = models.CharField(max_length=100, verbose_name="标题")
    image = models.ImageField(upload_to='banner/%Y/%m', verbose_name="轮播图", max_length=100)
    url = models.URLField(max_length=200, verbose_name="访问地址")
    index = models.IntegerField(default=100, verbose_name="顺序")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name_plural = verbose_name = "轮播图"

apps/users/views.py
# _*_ coding:utf-8 _*_

import json

from django.shortcuts import render, reverse, redirect, HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q
from django.views.generic import View
from pure_pagination import Paginator, PageNotAnInteger

from MxOnline.settings import FAV_TYPE
from .models import UserProfile, EmailVerifyRecord, Banner
from .forms import LoginForm, RegisterForm, ForgetForm, ModifyPwdForm, \
     UploadImageForm, UpdatePwdForm, ModifyEmailForm, ModifyUserForm
from utils.email_utils import send_register_email, email_is_exist
from utils.mixin_utils import LoginRequiredMixin
from operation.models import UserCourse, UserFavorite, UserMessage
from organization.models import Teacher, CourseOrg
from courses.models import Course

# Create your views here.


class CustomBackend(ModelBackend):
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            user = UserProfile.objects.get(Q(username=username) | Q(email=username))
            if user.check_password(raw_password=password):
                return user
        except Exception as e:
            print(e)
            return None


class LoginView(View):

    template_name = 'users/login.html'
    url = 'users:login'

    def get(self, request):
        context = {'login_form': LoginForm()}
        return render(request=request, template_name=self.template_name, context=context)

    def post(self, request):
        context = {'request': request}
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user_name = request.POST.get('username', '')
            pass_word = request.POST.get('password', '')
            user = authenticate(username=user_name, password=pass_word)
            if user is not None and user.is_active:
                login(request, user=user)
                self.url = 'index'
                return redirect(reverse(self.url), kwargs=context)
            else:
                context['msg'] = '用户名密码错误或用户未激活'
        else:
            context['login_form'] = login_form
        return render(request=request, template_name=self.template_name, context=context)


class LogoutView(LoginRequiredMixin, View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('index'))


class RegisterView(View):
    template_name = 'users/register.html'
    url = 'users:register'

    def get(self, request):
        context = {'register_form': RegisterForm()}
        return render(request=request, template_name=self.template_name, context=context)

    def post(self, request):
        register_form = RegisterForm(request.POST)
        context = {'request': request}
        if register_form.is_valid():
            user_name = request.POST.get('email', "")
            pass_word = request.POST.get('password', "")
            context['register_form'] = register_form
            if not email_is_exist(UserProfile, user_name):
                user_profile = UserProfile()
                user_profile.username = user_name
                user_profile.email = user_name
                user_profile.set_password(raw_password=pass_word)
                user_profile.is_active = False
                user_profile.save()
                user_message = UserMessage(user=user_profile.id, msg_body='欢迎注册在线学习教育网')
                user_message.save()

                send_register_email(user_name, 'register')
                context['msg'] = "注册成功，激活链接已发送到您的邮箱"
                self.template_name = 'users/login.html'
            else:
                context['msg'] = "该邮箱已被使用"
        else:
            context['register_form'] = register_form

        return render(request=request, template_name=self.template_name, context=context)


class ForgetPwdView(View):

    template_name = 'users/forgetpwd.html'
    url = 'users:forget'

    def get(self, request):
        forget_form = request.GET.get('forget_form', ForgetForm())
        context = {'forget_form': forget_form}
        return render(request, template_name=self.template_name, context=context)

    def post(self, request):
        context = {'request': request}
        forget_form = ForgetForm(request.POST)
        if forget_form.is_valid():
            email = request.POST.get('email', '')
            if email_is_exist(UserProfile, email):
                send_register_email(receiver=email, send_type='forget')
                self.url = 'users:mail_sent'
                return redirect(reverse(self.url))
            else:
                context['forget_form'] = forget_form
                context['msg'] = '账号非法或者不存在'
        else:
            context['forget_form'] = forget_form
        return render(request=request, template_name=self.template_name, context=context)


class ActivateUser(View):

    template_name = 'users/forgetpwd.html'
    url = 'users:activate'

    def get(self, request, active_code):
        context = {'request': request}
        email_rec = EmailVerifyRecord.objects.get(code=active_code)
        if email_rec and email_rec.valid:
            email = email_rec.email
            email_rec.valid = False
            email_rec.save()
            user = UserProfile.objects.get(email=email)
            user.is_active = True
            user.save()
            context['msg'] = '激活成功，请重新登录'
            self.template_name = "users/login.html"
            return render(request=request, template_name=self.template_name, context=context)
        else:
            self.url = 'users:expired'
            return redirect(reverse(self.url))


class ResetView(View):
    template_name = 'users/password_reset.html'
    url = 'users:reset'

    def get(self, request, reset_code):
        context = {'request': request}
        email_rec = EmailVerifyRecord.objects.get(code=reset_code)
        if email_rec and email_rec.valid:
            modify_form = ModifyPwdForm(initial={'reset_code': reset_code, 'email': email_rec.email})
            context['msg'] = '已经通过验证，请设置新密码,本页面刷新后失效'
            context['modify_form'] = modify_form
            return render(request=request, template_name=self.template_name, context=context)
        else:
            self.url = 'users:expired'
        return redirect(reverse(self.url), kwargs=context)


class PwdResetView(View):

    template_name = 'users/password_reset.html'
    url = 'users:pwd_reset'

    def get(self, request):
        modify_form = request.GET.get('modify_form', ModifyPwdForm())
        msg = request.GET.get('msg', '')
        context = {'modify_form': modify_form,
                   'msg': msg
                   }
        return render(request, template_name=self.template_name, context=context)

    def post(self, request):
        modify_form = ModifyPwdForm(request.POST)
        context = {'modify_form': modify_form,
                   'request': request}
        if modify_form.is_valid():
            reset_code = modify_form.data.get('reset_code', '')
            email_rec = EmailVerifyRecord.objects.get(code=reset_code)
            if email_rec.valid:
                email_rec.valid = False
                user = UserProfile.objects.get(email=email_rec.email)
                if user and user.is_active:
                    user.set_password(raw_password=modify_form.data.get('new_password', ''))
                    user.save()
                    context['msg'] = '重置成功，请重新登录'
                    email_rec.save()
                    self.template_name = 'users/login.html'
                else:
                    context['msg'] = '用户已注销或不存在'
            else:
                self.template_name = 'users/url_expired.html'
        else:
            context['msg'] = '输入有误，请重试'

        return render(request=request, template_name=self.template_name, context=context)


class IndexView(View):

    template_name = 'index.html'

    def get(self, request):
        #取出轮播图
        banners = Banner.objects.all().order_by('index')[:5]
        courses = Course.objects.all().order_by('fav_nums')[:6]
        banner_courses = Course.objects.filter(is_banner=True).order_by('fav_nums')[:3]

        context = {
            'org_list': CourseOrg.objects.all()[:15],
            'courses': courses,
            'banner_courses': banner_courses,
            'cur_page': 'index',
            'banners': banners,
        }
        return render(request=request, template_name=self.template_name, context=context)


class UserInfoCenter(LoginRequiredMixin, View):
    """
    用户个人信息
    """
    template_name = 'users/usercenter-info.html'
    url = 'users:home'

    def get(self, request):
        image_form = UploadImageForm()
        context = {'image_form': image_form}
        return render(request, context=context, template_name=self.template_name)

    def post(self, request):
        user_info = ModifyUserForm(request.POST, instance=request.user)
        context = {}
        if user_info.is_valid():
            user_info.save()
            context['status'] = 'success'
            context['msg'] = '资料更改成功'
        else:
            context['status'] = 'fail'
            context['msg'] = list(user_info.errors.values())[0]
        return HttpResponse(content=json.dumps(context), content_type='application/json')


class UploadImageView(LoginRequiredMixin, View):

    def post(self, request):
        context = {}
        image_form = UploadImageForm(request.POST, request.FILES, instance=request.user)
        if image_form.is_valid():
            image_form.save(commit=True)
            context['status'] = 'success'
            context['msg'] = '头像更改成功'
        else:
            context['status'] = 'fail'
            context['msg'] = list(image_form.errors.values())[0]
        return HttpResponse(content=json.dumps(context), content_type='application/json')


class UpdatePasswordView(View):

    def post(self, request):

templates/users/password_reset.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>{{ msg }}</p>
        <form id="reset_password_form" action="{% url 'users:pwd_reset' %}" method="post">
            {% csrf_token %}
            <ul>
                <li>
                    {{ modify_form.email }}
                </li>
                <li>
                    {{ modify_form.reset_code }}
                </li>
                <li>
                    <span class="">新 密 码 ：</span>
                    {{ modify_form.old_password }}
                    <i></i>
                </li>
                <li>
                    <span class="">确定密码：</span>
                    {{ modify_form.new_password }}
                    <i></i>
                </li>
                <li class="button">
                    <input type="submit"  value="提交" >
                </li>
            </ul>
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="{% static 'images/check2.png' %}">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

templates/users/send_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>慕学在线</title>
</head>
<body>
    <p>邮件已发送, 请查收</p>
</body>
</html>

templates/users/url_expired.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>慕学在线</title>
</head>
<body>
<p>链接失效</p>
</body>
</html>

templates/users/usercenter-fav-course.html
{% extends 'users/usercenter.html' %}
{% load staticfiles %}
{% block title %}我的收藏- 在线学习网{% endblock %}

{% block custom_crumbs %}
<!--crumbs start-->
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:home' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
<section>
	<div class="wp list personal_list">
	<div class="left">
        <ul>
            <li ><a href="{% url 'users:home' %}">个人资料</a></li>
            <li ><a href="{% url 'users:course' %}">我的课程</a></li>
            <li class="active2"><a href="{% url 'users:favcourse' %}">我的收藏</a></li>
            <li >
                <a href="{% url 'users:message' %}" style="position: relative;">
                    我的消息
                </a>
            </li>
        </ul>
	</div>
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:favorg'  %}">课程机构</a> </li>
                        <li><a href="{% url 'users:favteacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'users:favcourse' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in fav_courses %}
                        <div class="module1_5 box">
                            <a href="{% url 'courses:detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'courses:detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}分钟</i></span>
                                <span class="fr">学习人数：{{ course.get_students_cnt }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favtype="course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                        {%  endfor %}
                    </div>
                </div>
            </div>
        </div>
	</div>
</section>
{% endblock %}

templates/users/usercenter-fav-org.html
{% extends 'users/usercenter.html' %}
{% load staticfiles %}
{% block title %}我的收藏- 在线学习网{% endblock %}

{% block custom_crumbs %}
<!--crumbs start-->

    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:home' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
<section>
	<div class="wp list personal_list">
	<div class="left">
        <ul>
            <li ><a href="{% url 'users:home' %}">个人资料</a></li>
            <li ><a href="{% url 'users:course' %}">我的课程</a></li>
            <li class="active2"><a href="{% url 'users:favorg' %}">我的收藏</a></li>
            <li >
                <a href="{% url 'users:message' %}" style="position: relative;">
                    我的消息
                </a>
            </li>
        </ul>
	</div>
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'users:favorg' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:favteacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:favcourse' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for org in fav_orgs %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'orgs:home' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'orgs:home' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">
                                    <img src="{% static '/images/authentication.png' %}"/>
                                    <img src="{% static 'images/gold.png' %}"/>
                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}" data-favtype="corg"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
        </div>
	</div>
</section>

{% endblock %}

templates/users/usercenter-fav-teacher.html
{% extends 'users/usercenter.html' %}
{% load staticfiles %}
{% block title %}我的收藏- 慕学在线网{% endblock %}
{% block custom_crumbs %}
<!--crumbs start-->

    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:home' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
<section>
	<div class="wp list personal_list">
	<div class="left">
        <ul>
            <li ><a href="{% url 'users:home' %}">个人资料</a></li>
            <li ><a href="{% url 'users:course' %}">我的课程</a></li>
            <li class="active2"><a href="{% url 'users:favorg' %}">我的收藏</a></li>
            <li >
                <a href="{% url 'users:message' %}" style="position: relative;">
                    我的消息
                </a>
            </li>
        </ul>
	</div>

    
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:favorg' %}">课程机构</a> </li>
                        <li class="active"><a href="{% url 'users:favteacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:favcourse' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for teacher in fav_teachers %}
                    <div class=" butler_list butler-fav-box">
                        <dl class="des users">
                            <dt>
                                <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                    <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1>
                                    <a href="{% url 'orgs:teacher_detail' teacher.id %}">
                                        {{ teacher.name }}
                                        {% if teacher.is_veryfied %}
                                        <span class="key">认证教师</span>
                                        {% endif %}
                                    </a>
                                </h1>
                                <ul class="cont clearfix">
                                    <li class="time">工作年限：<span>{{ teacher.work_years }}年</span></li>
                                    <li class="c7">课程数：<span>{{ teacher.get_course_count }}</span></li>
                                </ul>
                                <ul class="cont clearfix">
                                    <li class="time">工作公司：<span>{{ teacher.work_compay }}</span></li>
                                    <li class="c7">公司职位：<span>{{ teacher.position }}</span></li>
                                </ul>
                            </dd>
                            <div class="delete jsDeleteFav_teacher" data-favtype="teacher" data-favid="{{ teacher.id }}"></div>
                        </dl>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
	</div>
</section>
{% endblock %}

templates/users/usercenter-mycourse.html
{% extends 'users/usercenter.html' %}
{% load staticfiles %}
{% block title %}我的课程- 慕学在线网{% endblock %}
{% block custom_crumbs %}
<!--crumbs start-->
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:home' %}">个人中心</a>></li>
                <li>我的课程</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
<section>
	<div class="wp list personal_list">
	<div class="left">
        <ul>
            <li ><a href="{% url 'users:home' %}">个人资料</a></li>
            <li class="active2"><a href="{% url 'users:course' %}">我的课程</a></li>
            <li ><a href="{% url 'users:favorg' %}">我的收藏</a></li>
            <li >
                <a href="{% url 'users:message' %}" style="position: relative;">
                    我的消息
                </a>
            </li>
        </ul>
	</div>

    
    <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的课程</h1>
			</div>
		</div>
		<div class="personal_des permessage">
			<div class="companycenter">
				<div class="group_list brief">
                    {% for user_course in courses %}
                    <div class="module1_5 box">
                            <a href="{% url 'courses:detail' user_course.course.id %}">
                                <img width="214" height="190" class="scrollLoading" src="{{ MEDIA_URL }}{{ user_course.course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'courses:detail' user_course.course.id %}"><h2>{{ user_course.course.name }}</h2></a>
                                <span class="fl">课时：<i class="key">{{ user_course.course.learn_times }}分钟</i></span>
                                <span class="fr">学习人数：{{ user_course.course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ user_course.course.course_org.name }}</span>
                                <span class="star fr  notlogin" data-favid="{{ user_course.course.id }}">{{ user_course.course.fav_nums }}</span>
                            </div>
                        </div>
                    {% endfor %}
				</div>
			</div>
		</div>
	</div>
	</div>
</section>
{% endblock %}